# Creation of the service
apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    # NodePort (Node), Port (Service), TargetPort (Container)
    - port: 80 # Service
      targetPort: 80 # Container