apiVersion: v1
kind: Pod
metadata:
  name: live-http-pod
spec:
  containers:
    - image: busybox
      name: busybox
      command:
        - 'sh'
        - '-c'
        - 'echo live http testing && sleep 3600'
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
