apiVersion: apps/v1
kind: Deployment
metadata:
  name: na-req-pref-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: na-req-pref-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
             - matchExpressions:
                - key: cpu
                  operator: In
                  values:
                    - intel
                    - amd
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                - key: dc
                  operator: In
                  values:
                    - mumbai

