#Creation of the deployment
apiVersion: apps/v1
kind: Deployment
metadata:
   name: nginx-deploy
spec:
  # Creating replicas
   replicas: 2
   selector:
     matchLabels:
         app: UI
  # Pod template
   template:
     metadata:
        name: nginx-pod
        labels:
          app: UI
     spec:
        containers:
         - name: nginx-container
           image: nginx