apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-dev-role-binding
  namespace: ms-cluster-dev
subjects:
  - kind: User
    name: uma
    apiGroup: rbac.authorization.k8s.io
roleRef:
    kind: ClusterRole
    name: cluster-dev-role
    apiGroup: rbac.authorization.k8s.io
