apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-dev-role
  namespace: ms-cluster-dev
rules:
 - apiGroups: [""]
   resources: ["persistentvolumes"]
   verbs: ["get", "create", "list"]