apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: token
    server: https://10.128.0.3:6443
  name: dev-cluster
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: umacreds
  user:
    client-certificate: /home/uma/uma.crt
    client-key: /home/uma/uma.key