apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-role
  namespace: ms-dev
rules: # pods, deployements > create, list
  - apiGroups: ["", "apps"]
    resources: ["pods", "deployments"]
    verbs: ["get", "create", "list"]

