apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-role-binding
  namespace: ms-dev
subjects:
  - kind: User
    name: uma
    apiGroup: rbac.authorization.k8s.io
roleRef:
    kind: Role
    name: dev-role
    apiGroup: rbac.authorization.k8s.io

