apiVersion: v1
kind: Pod
metadata:
  name: faster-pvc-pod
spec:
  containers:
   -  name: nginx
      image: nginx
      volumeMounts:
        - name: pvc-sc
          mountPath: "/logging"
  volumes:
    - persistentVolumeClaim:
        claimName: pvc-test
      name: pvc-sc
