apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test
  namespace: ms-dev
spec:
  storageClassName: faster-ssd
  resources:
    requests:
      storage: 15Gi
  accessModes:
    - ReadWriteOnce