apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-taint-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: no-taint-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
