apiVersion: v1
kind: Pod
metadata:
  name: resource-pod
spec:
  containers:
    - image: busybox
      name: busybox
      command:
        - 'sh'
        - '-c'
        - 'Echo Resource Requests & Limits && sleep 3600'
      resources:
        requests:
          memory: '128Mi'
          cpu: '250m'
        limits:
          memory: '250Mi'
          cpu: '500m'