apiVersion: v1
kind: Pod
metadata:
  name: on-failure-pod
spec:
  containers:
    - image: busybox
      name: busybox
      command:
        - 'sh'
        - '-c'
        - 'sleep 10 & thiswillgetfailed'
  restartPolicy: OnFailure