apiVersion: v1
kind: Pod
metadata:
  name: env-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'echo My Name is : $CONFIGMAPNAME && sleep 3600']
      env:
       - name: CONFIGMAPNAME
         valueFrom:
           configMapKeyRef:
             name: data-config
             key: name
