apiVersion: v1
kind: Pod
metadata:
  name: env-from-pod
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["sleep", "3600"]
      envFrom:
        - configMapRef:
            name: data-config
