apiVersion: v1
kind: Pod
metadata:
  name: config-volume-pod
spec:
  containers:
    - image: busybox
      name: busybox
      command:
        - 'sh'
        - '-c'
        - 'cat Name : /config/name'
      volumeMounts:
        - name: config-volume
          mountPath: "/config"
  volumes:
    - name: config-volume
      configMap:
         name: data-config