apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - 'sh'
        - '-c'
        - 'echo $CONFIGMAPNAME can get DB_SERVER_NAME: $DB_SERVER_NAME && sleep 3600'
      env:
       - valueFrom:
          configMapKeyRef:
            name: data-config
            key: name
         name: CONFIGMAPNAME
       - valueFrom:
          secretKeyRef:
            name: config-data
            key: DB_SERVER_NAME
         name: DB_SERVER_NAME
